services:
  api:
    build: .
    container_name: mailvetter-api
    restart: always
    environment: 
      - PORT=8080
      - HIBP_API_KEY=${HIBP_API_KEY}
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    expose:
      - "8080"
    networks:
      - mv-net

  # The Web Server
  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from mailvetter.com --to api:8080
    networks:
      - mv-net
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  redis:
    image: redis:8.4.1-alpine
    container_name: mailvetter-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mv-net

volumes:
  caddy_data:
  caddy_config:

networks:
  mv-net:
    driver: bridge