services:
  api:
    build: .
    container_name: mailvetter-api
    restart: always
    command: ["./api-server"]
    environment: 
      - PORT=8080
      - HIBP_API_KEY=${HIBP_API_KEY}
      - REDIS_ADDR=redis:6379
      - DB_URL=DB_URL=postgres://mv_user:mv_password@postgres:5432/mailvetter_db?pool_max_conns=100
      - PROXY_LIST=${PROXY_LIST}
    depends_on:
      - redis
      - postgres
    expose:
      - "8080"
    networks:
      - mv-net

  worker:
    build: .
    container_name: mailvetter-worker
    command: ["./worker-process"]
    restart: always
    environment:
      - HIBP_API_KEY=${HIBP_API_KEY}
      - REDIS_ADDR=redis:6379
      - DB_URL=DB_URL=postgres://mv_user:mv_password@postgres:5432/mailvetter_db?pool_max_conns=100
      - PROXY_LIST=${PROXY_LIST}
      - WORKER_CONCURRENCY=50
    networks:
      - mv-net
    depends_on:
      - redis
      - postgres

  # The Web Server
  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from mailvetter.com --to api:8080
    networks:
      - mv-net
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  redis:
    image: redis:8.4.1-alpine
    container_name: mailvetter-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mv-net

  postgres:
    image: postgres:18-alpine
    container_name: mailvetter-postgres
    restart: always
    environment:
      POSTGRES_USER: mv_user
      POSTGRES_PASSWORD: mv_password
      POSTGRES_DB: mailvetter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mv-net

volumes:
  caddy_data:
  caddy_config:
  postgres_data:

networks:
  mv-net:
    driver: bridge
